#!/usr/bin/env python3
"""Packaging bounds, source allowlist, reproducibility and tamper rejection."""
import io
from pathlib import Path
import sys
import tarfile
import tempfile
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
import package_preview as package


class PackageTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="stun-package-test-")
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)

    def fixture(self):
        source = self.root / "fixture"
        (source / "packaging").mkdir(parents=True)
        (source / "README.md").write_text("STUN fixture\n")
        (source / "packaging/source-files.txt").write_text("README.md\npackaging/source-files.txt\n")
        return source

    def test_allowlist_excludes_history_secrets_and_cache(self):
        source = self.fixture()
        (source / ".git").mkdir()
        (source / ".git/config").write_text("private remote")
        (source / "private.key").write_text("never export")
        (source / "build").mkdir()
        (source / "build/debug.log").write_text("private build log")
        entries = package.snapshot(source, self.root / "snapshot")
        self.assertEqual(set(entries), {"README.md", "packaging/source-files.txt"})
        self.assertEqual(set(package.tree_files(self.root / "snapshot")), set(entries))

    def test_reject_path_escape_duplicates_missing_and_history(self):
        source = self.fixture()
        for name in ["../outside", "/etc/passwd", "README.md\nREADME.md",
                     ".git/config", "missing.cc", "file with spaces", "./README.md"]:
            with self.subTest(name=name):
                (source / "packaging/source-files.txt").write_text(name + "\n")
                with self.assertRaises(ValueError):
                    package.inventory(source)

    def test_generated_cache_cannot_enter_source_archive(self):
        source = self.fixture()
        target = self.root / "snapshot"
        entries = package.snapshot(source, target)
        package.verify_snapshot(target, entries)
        (target / "__pycache__").mkdir()
        (target / "__pycache__/test.pyc").write_bytes(b"generated bytecode")
        with self.assertRaises(ValueError):
            package.verify_snapshot(target, entries)

    def test_reject_symlink_and_credentials(self):
        source = self.fixture()
        outside = self.root / "outside"
        outside.write_text("outside")
        (source / "linked").symlink_to(outside)
        (source / "packaging/source-files.txt").write_text("linked\n")
        with self.assertRaises(ValueError):
            package.inventory(source)
        (source / "packaging/source-files.txt").write_text("README.md\n")
        (source / "README.md").write_text("-----BEGIN " + "OPENSSH PRIVATE KEY-----")
        with self.assertRaises(ValueError):
            package.inventory(source)

    def test_complete_version_matched_libuv_notices(self):
        project = Path(__file__).resolve().parents[1]
        reviewed = project / "packaging/licenses/libuv-1.52.1.txt"
        contents = package.checked_libuv_notices(project, "1.52.1", reviewed)
        for marker in [b"--- LICENSE ---", b"--- LICENSE-extra ---", b"--- src/inet.c ---",
                       b"--- include/uv/tree.h ---", b"Copyright Joyent", b"Niels Provos",
                       b"Internet Systems Consortium", b"Ben Noordhuis", b"src/heap-inl.h",
                       b"src/queue.h"]:
            self.assertIn(marker, contents)
        with self.assertRaises(ValueError):
            package.checked_libuv_notices(project, "1.44.2", reviewed)
        partial = self.root / "incomplete-license"
        partial.write_bytes(b"libuv Permission copyright MIT only")
        with self.assertRaises(ValueError):
            package.checked_libuv_notices(project, "1.52.1", partial)

    def test_archive_reproducible_and_no_overwrite(self):
        source = self.fixture()
        package.describe(source, {"channel": "development-preview", "published": False})
        first, second = self.root / "one.tar.gz", self.root / "two.tar.gz"
        package.archive(source, first, "sovkit-stun-test")
        package.archive(source, second, "sovkit-stun-test")
        self.assertEqual(first.read_bytes(), second.read_bytes())
        with self.assertRaises(FileExistsError):
            package.archive(source, first, "sovkit-stun-test")

    def test_modified_payload_rejected(self):
        source = self.fixture()
        package.describe(source, {"channel": "development-preview", "published": False})
        (source / "README.md").write_text("tampered")
        with self.assertRaises(ValueError):
            package.archive(source, self.root / "bad.tar.gz", "sovkit-stun-test")

    def test_unsafe_archive_member_rejected(self):
        for name in ["../escape", "/absolute/path"]:
            destination = self.root / "unsafe.tar.gz"
            with tarfile.open(destination, "w:gz") as tar:
                info = tarfile.TarInfo(name)
                info.size = 1
                tar.addfile(info, io.BytesIO(b"x"))
            with self.assertRaises(ValueError):
                package.verify_archive(destination)

    def test_official_claim_rejected(self):
        source = self.fixture()
        package.describe(source, {"channel": "stable", "published": True})
        with self.assertRaises(ValueError):
            package.archive(source, self.root / "stable.tar.gz", "sovkit-stun-test")


if __name__ == "__main__":
    unittest.main(verbosity=2)
