# A stable dependency target, resolved again on the SDK consumer's machine.
if(TARGET SovkitStun::libuv)
  return()
endif()
find_package(libuv 1.44 CONFIG QUIET)
if(TARGET libuv::uv_a)
  set(_stun_uv_target libuv::uv_a)
elseif(TARGET libuv::uv)
  set(_stun_uv_target libuv::uv)
else()
  find_package(PkgConfig QUIET)
  if(PkgConfig_FOUND)
    pkg_check_modules(STUN_LIBUV QUIET IMPORTED_TARGET libuv>=1.44)
  endif()
  if(NOT TARGET PkgConfig::STUN_LIBUV)
    return()
  endif()
  set(_stun_uv_target PkgConfig::STUN_LIBUV)
endif()
add_library(SovkitStun::libuv INTERFACE IMPORTED)
set_property(TARGET SovkitStun::libuv PROPERTY
  INTERFACE_LINK_LIBRARIES ${_stun_uv_target})
unset(_stun_uv_target)
